name: Lee Loo Lee
title: Lee Loo Lee Laa | As you wish
description: lee loo lee's personal blog
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: yunscien@naver.com
disqus_username: disqus_username
